
// auth
export const REPLACE_DATA_AUTH = "REPLACE_DATA_AUTH";
export const REPLACE_DATA_2_AUTH = "REPLACE_DATA_2_AUTH";

// basic
export const REPLACE_READY = "REPLACE_READY";
export const REPLACE_LOADING = "REPLACE_LOADING";
export const REPLACE_WORKING = "REPLACE_WORKING";
export const REPLACE_AUTHORITY = "REPLACE_AUTHORITY";

export const REPLACE_DATA = "REPLACE_DATA";
export const REPLACE_DATA_2 = "REPLACE_DATA_2";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";


// hots
export const REPLACE_DATA_HOTS = "REPLACE_DATA_HOTS";
export const REPLACE_DATA_2_HOTS = "REPLACE_DATA_2_HOTS";

// hots
export const REPLACE_DATA_HERO = "REPLACE_DATA_HERO";
export const REPLACE_DATA_2_HERO = "REPLACE_DATA_2_HERO";


// stats
export const REPLACE_DATA_PLAYER = "REPLACE_DATA_PLAYER";
export const REPLACE_DATA_2_PLAYER = "REPLACE_DATA_2_PLAYER";


// react
export const REPLACE_DATA_REACTION = "REPLACE_DATA_REACTION";
export const REPLACE_DATA_2_REACTION = "REPLACE_DATA_2_REACTION";


// team_planner
export const REPLACE_DATA_TEAM_PLANNER = "REPLACE_DATA_TEAM_PLANNER";
export const REPLACE_DATA_2_TEAM_PLANNER = "REPLACE_DATA_2_TEAM_PLANNER";


export const REPLACE_PLAN_TEAM = "REPLACE_PLAN_TEAM";

export const REPLACE_PLAYER_TAGS = "REPLACE_PLAYER_TAGS";
export const REPLACE_PLAYER_STATUS = "REPLACE_PLAYER_STATUS";
export const REPLACE_REGION = "REPLACE_REGION";
export const REPLACE_NUMBER = "REPLACE_NUMBER";

export const ADD_RESULT = "ADD_RESULT";
export const DELETE_RESULT = "DELETE_RESULT";


// comp-gallery
export const REPLACE_DATA_COMP_GALLERY = "REPLACE_DATA_COMP_GALLERY";
export const REPLACE_DATA_2_COMP_GALLERY = "REPLACE_DATA_2_COMP_GALLERY";

export const REPLACE_LIST_POSITION = "REPLACE_LIST_POSITION";

/*
export const REPLACE_LIST_MAP = "REPLACE_LIST_MAP";

export const REPLACE_WHICH_ADDING = "REPLACE_WHICH_ADDING";
export const REPLACE_LOCATION_ADDING_HERO = "REPLACE_LOCATION_ADDING_HERO";
export const REPLACE_LOCATION_ADDING_MAP = "REPLACE_LOCATION_ADDING_MAP";

export const REPLACE_ID_MAP_CHOSEN = "REPLACE_ID_MAP_CHOSEN";
export const REPLACE_ID_HERO_CHOSEN = "REPLACE_ID_HERO_CHOSEN";
*/