export const REPLACE_READY = "REPLACE_READY";
export const REPLACE_LOADING = "REPLACE_LOADING";
export const REPLACE_WORKING = "REPLACE_WORKING";
export const REPLACE_AUTHORITY = "REPLACE_AUTHORITY";

export const REPLACE_DATA = "REPLACE_DATA";
export const REPLACE_DATA_2 = "REPLACE_DATA_2";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const ADD_RESULT = "ADD_RESULT";
export const DELETE_RESULT = "DELETE_RESULT";

export const REPLACE_PLAYER_TAGS = "REPLACE_PLAYER_TAGS";
export const REPLACE_PLAYER_STATUS = "REPLACE_PLAYER_STATUS";
export const REPLACE_REGION = "REPLACE_REGION";
export const REPLACE_NUMBER = "REPLACE_NUMBER";
